### ISSUE TITLE
No longer recognizing NYT Wordle page

### ISSUE THREAD

**Issue by neilltMLH** [mysticuno/wordle-helper#8]
The extension has been working great for months!  However now it acts as if the browser is not on the wordle page and just displays "Open Today's Wordle" which when clicked just opens another tab to the same Wordle page, and the loop continues.

**Comment by neillt** [comment]
Awesome, thank you!!!!  If you do PayPal or Buy me a Coffee or whatever let me know and I will chuck some cash your way!

**Comment by mysticuno** [comment]
Thank you for pointing this issue out! It looks like it was due a change in the key that is used to store Wordle settings in the browser storage. I've gone ahead and submitted a new version to the Chrome Web Store, which should be auto-published in a few days after it's reviewed. If you'd like, you can clone the repo locally and load the unpacked version of the extension while it's in review.
